version: "3.9"
#  后端服务单纯模式
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      PORT: 3000
      BACKEND_URL: http://localhost